### ISSUE TITLE
Empty caption does not delete map

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-plugin-map#10]
Once a map is created, it is not possible to delete it by removing the caption text.

**Comment by WardCunningham** [comment]
The current double-click editing attempts to keep the map visible so that scrolling and zooming while editing preserves these properties. I've reverted this behavior so that the usual delete processing works and intend to derive the initial view from markup.

Work in progress here: https://github.com/clemsos/wiki-plugin-map/pull/7

**Comment by WardCunningham** [comment]
This fixed and committed, pending a pull request from @clemsos.
