### ISSUE TITLE
places-together does not wait for left-handed instances to load

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-plugin-map#16]
I want to show off Federated Wiki to the wiki mapping colleagues from https://commonsspace.hackpad.com/ with whom we are going to run a mapping event at the WSF.

Unfortunately manufactoring the link http://ward.asia.wiki.org/view/welcome-visitors/home.ward.asia.wiki.org/at-home-in-michigan-city/home.ward.asia.wiki.org/at-home-on-prairie-ave/home.ward.asia.wiki.org/at-home-in-munster/home.ward.asia.wiki.org/at-home-in-owen-hall/home.ward.asia.wiki.org/at-home-on-vine-st/home.ward.asia.wiki.org/places-together not to display the western extent does not yield the expected result: All the five dots together on one map.

It seems Places Together could be a little more patient and wait for the other map plugins to finish display.

**Comment by WardCunningham** [comment]
Yes, this all pages at once case suffers from the timing issue you have observed. We have a solution but the solution has not been coded and introduces some inconvenience to plugin authors that we have not yet faced. I will describe how we intend to create exactly the patience you suggest. Then I will describe the compromise that we live with today.

### Ideal

A plugin is rendered in two steps, `emit` and `bind`. When many plugins are rendered at once all of the emits are called first, then when the slowest completes, all of the binds are called.  A plugin that offers to be a source of data must show this in what it emits. A plugin that wants to consume data from others must delay these connections until it binds.

### Compromise

A plugin is rendered in two steps, `emit` and `bind` that follow each other without intervening activity. As a consequence there is little difference between the two handlers. We see plugins concentrating all emitting and binding into only one step. The Map plugin does this so that it can keep track of the Leaflet instance between drawing the map and rendering LINEUP markers. 

### Future

I look forward to seeing this limitation eliminated. It hurts me to explain it here and in the dev hacking guide. http://dev.asia.wiki.org/view/hacking-federated-wiki/view/render-pages

**Comment by WardCunningham** [comment]
The Bikeshare plugin retrieves data from system operator's websites. This is slow so I haven't even tried to fit the refresh into the cycle I described above. My current approach is to report:

        waiting for stations

when the plugin renders and then update this to:

        540 stations

when the data arrives. The plugin offers to source markers but returns an empty array while waiting. The map can't even know what region it should be showing before the stations arrive. Perhaps it should default to a world view, register for a "data available" event that we don't yet have, and then draw the right map when it does arrive. 

If we generalize this to multiple sources it would mean that the map might jump around while each dataset arrives. Maybe the map could zoom in slowly hoping that all data is available by the time it gets to the right scale.

**Comment by paul90** [comment]
Going to close this, some of the internals have changes since this issue was raised which has changed how plugins in a line are rendered. As far as I can see the example lineup is working as expected with the 5 markers on the map, though two pairs are so close so they overlay each other.

The Bikeshare plugin, will likely need a slight change to notify the lineup when it has data available.

**Comment by almereyda** [comment]
Thank you Paul for spotting this. Usually Leaflet cluster markers help very well to draw markers nearby. I'll have a try to validate this hypothesis, once (as in eventually) I get a suitable fedwiki development environment working.
